### PR TITLE
Prepared CSS for Production

### PR DESCRIPTION
**Pull request by bennias**
- [x] Renamed 'style.css' > 'demo.css'.
- [x] Renamed 'container' > 'cal__container' to avoid implementing issues.
- [x] Added RFP CSS-File 'dist/style.min.css' | Removed demo classes / prefixed and minified.

### CODE REVIEW

**Comment by bennias** [comment]
@chrisssycollins I will do a new PR for the Language-selection when this one is merged. 👍

**Comment by chrissy-dev** [comment]
@bennias Good idea removing the demo CSS from the `./dist`.  In the future I'll probably end up adding a build script to do this 👍 . Happy to merge this.

**Comment by bennias** [comment]
@chrisssycollins Thanks! So I will do another PR for the Language? Which build tool do you prefer?

**Comment by chrissy-dev** [comment]
@bennias Yeah, another PR for the language with default being English would be cool. As for build tool I'm not sure yet, could have a very minimal Gulpfile.

I like the simplicity of the project which is encouraging people to fork it hack away without doing much so would like to keep any build scripts to a minimal.

**Pull request merged**
